### ISSUE TITLE
Issue with running `node` in Windows system

### ISSUE THREAD

**Issue by marklcrns** [cse110-sp23-group15/cse110-sp23-group15#10]
Further investigate.

Might have something to do with `node:fs.readdirSync` function. 

# Windows
![image](https://user-images.githubusercontent.com/52873993/234086923-ad56eebd-e2a6-4300-aa0b-eb9aa6ba1bd7.png)

# Linux
![image](https://user-images.githubusercontent.com/52873993/234087341-32ffea63-c1b2-4e08-be27-36e6ed9a947b.png)

**Comment by hdpham22** [comment]
For Magic 8-ball. Outdated
