### ISSUE TITLE
`noodlesResult.js` need to use different localStorage key other than `noodleIndex`

### ISSUE THREAD

**Issue by marklcrns** [cse110-sp23-group15/cse110-sp23-group15#131]
`noodleIndex` is already used in `profiles.js` so even if a user has never answered the questionnaire, our app will think they have already once they view the Noodles Profile page before going to the questionnaire

- Suggestion. Use `myNoodleIndex` instead of `noodleIndex`
- Need to change `noodleIndex` key in both `fortune.js` and `noodlesResult.js`

**Comment by damiyu** [comment]
The index issue is solved and the user is now directed to the questionnaire if they haven't taken the quiz.
