### ISSUE TITLE
Create Frontend Wireframe

### ISSUE THREAD

**Issue by marklcrns** [cse110-sp23-group15/cse110-sp23-group15#21]
Create a Frontend wireframe for how our app will look at every step

- Default page design
- Pre/Post animation design
- Menu interaction

**Comment by hdpham22** [comment]
Mobile and Desktop wireframes completed here
https://www.figma.com/file/xMDGw4FwyA8KfdYPyGJekg/Magic-8-Ball-Wireframe?type=design&node-id=0-1&t=KJph8YoNL62UpDiW-0
